# Generated by Django 2.2.9 on 2020-03-02 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('desc', wagtail.core.fields.RichTextField(blank=True)),
                ('per_page', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('events_date_filter', models.CharField(choices=[('current_future', 'Current and Future Events'), ('future', 'Future Events'), ('past_current', 'Past and Current Events'), ('past', 'Past Events')], default='current_future', help_text='Select how to filter events by date on this index listing page.', max_length=32)),
                ('events_date_order', models.CharField(choices=[('-start_date', 'Event Start Date (Reverse)'), ('start_date', 'Event Start Date'), ('-end_date', 'Event End Date (Reverse)'), ('end_date', 'Event End Date')], default='-start_date', help_text='Select how to sort events by start/end date on filtered events', max_length=32)),
                ('display_title', models.BooleanField(default=True)),
                ('display_desc', models.BooleanField(default=False)),
                ('no_listing_text', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
