# Generated by Django 2.0.8 on 2019-02-06 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.forms.widgets
import sitecore.blocks
import sitecore.parsers
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('level', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6')], widget=django.forms.widgets.RadioSelect)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Optional sub-heading in small text', required=False))])), ('markdown', sitecore.blocks.MarkdownAndShortcodeTextBlock(label='Markdown Paragraph')), ('paragraph', sitecore.blocks.ShortcodeRichTextBlock(label='Rich Text Paragraph')), ('blockquote', wagtail.core.blocks.StructBlock([('quote', sitecore.blocks.ShortcodeRichTextBlock(required=True)), ('footer', wagtail.core.blocks.CharBlock(required=False)), ('cite', wagtail.core.blocks.CharBlock(required=False)), ('reverse', wagtail.core.blocks.BooleanBlock(help_text='Check to right-align the quote', required=False))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('docs', wagtail.documents.blocks.DocumentChooserBlock(template='bootstrapblocks/document.html')), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external', wagtail.core.blocks.URLBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock()), ('code', wagtail.core.blocks.StructBlock([('lang', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash')])), ('code', wagtail.core.blocks.TextBlock(required=True)), ('hl_lines', sitecore.blocks.CSVIntListCharBlock(required=False)), ('line_nums', wagtail.core.blocks.BooleanBlock(help_text='Check to include line numbers', required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='bootstrapblocks/table.html')), ('carousel', wagtail.snippets.blocks.SnippetChooserBlock(sitecore.blocks.CarouselSnippet, template='bootstrapblocks/carousel.html'))], validators=[sitecore.parsers.ValidateCoreBlocks])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
