# Generated by Django 2.2.9 on 2020-03-02 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sitecore.blocks
import sitecore.parsers
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('splash_content', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'hr', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'display-1', 'display-2', 'display-3', 'display-4', 'h1', 'h2', 'h3', 'h4'], label='Rich Text Paragraph')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('docs', wagtail.documents.blocks.DocumentChooserBlock(template='bootstrapblocks/document.html')), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('carousel', wagtail.snippets.blocks.SnippetChooserBlock(sitecore.blocks.CarouselSnippet, template='bootstrapblocks/carousel.html'))], blank=True, help_text='Provide content for the splash area here.')),
                ('intro', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'hr', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'display-1', 'display-2', 'display-3', 'display-4', 'h1', 'h2', 'h3', 'h4'], label='Rich Text Paragraph')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('docs', wagtail.documents.blocks.DocumentChooserBlock(template='bootstrapblocks/document.html')), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('carousel', wagtail.snippets.blocks.SnippetChooserBlock(sitecore.blocks.CarouselSnippet, template='bootstrapblocks/carousel.html'))], blank=True, help_text='Provide introductory content here.')),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(label='Rich Text Paragraph')), ('markdown', sitecore.blocks.MarkdownAndShortcodeTextBlock(label='Markdown Paragraph')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('docs', wagtail.documents.blocks.DocumentChooserBlock(template='bootstrapblocks/document.html')), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('code', wagtail.core.blocks.StructBlock([('lang', sitecore.blocks.Select2ChoiceBlock(choices=[('', 'Please select a language for syntax highlighting'), ('python3', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash')])), ('code', wagtail.core.blocks.TextBlock(required=True)), ('hl_lines', sitecore.blocks.CSVIntListCharBlock(required=False)), ('line_nums', wagtail.core.blocks.BooleanBlock(help_text='Check to include line numbers', required=False))])), ('carousel', wagtail.snippets.blocks.SnippetChooserBlock(sitecore.blocks.CarouselSnippet, template='bootstrapblocks/carousel.html')), ('icon_card_deck', wagtail.snippets.blocks.SnippetChooserBlock(sitecore.blocks.IconCardDeckSnippet, template='bootstrapblocks/icon_card_deck.html'))], blank=True, help_text='Provide main body of content here.', validators=[sitecore.parsers.ValidateCoreBlocks])),
                ('display_title', models.BooleanField(default=True, help_text='Toggle the display of the default title field.')),
                ('splash_text_align', models.CharField(choices=[('text-justify', 'Justify'), ('text-left', 'Left'), ('text-center', 'Centre'), ('text-right', 'Right')], default='text-center', max_length=128)),
                ('splash_text_colour', models.CharField(choices=[('text-primary', 'Primary'), ('text-secondary', 'Secondary'), ('text-light', 'Light'), ('text-dark', 'Dark'), ('text-white', 'White'), ('text-body', 'Body'), ('text-muted', 'Muted'), ('text-white-50', 'White-50'), ('text-black-50', 'Black-50'), ('text-success', 'Success'), ('text-danger', 'Danger'), ('text-warning', 'Warning'), ('text-info', 'Info')], default='text-white', max_length=128)),
                ('splash_bg_colour', models.CharField(choices=[('bg-primary', 'Primary'), ('bg-secondary', 'Secondary'), ('bg-transparent', 'Transparent'), ('bg-light', 'Light'), ('bg-dark', 'Dark'), ('bg-white', 'White'), ('bg-success', 'Success'), ('bg-danger', 'Danger'), ('bg-warning', 'Warning'), ('bg-info', 'Info')], default='bg-transparent', max_length=128)),
                ('splash_border_radius', models.IntegerField(default='15', validators=[django.core.validators.MinValueValidator(0)])),
                ('intro_text_align', models.CharField(choices=[('text-justify', 'Justify'), ('text-left', 'Left'), ('text-center', 'Centre'), ('text-right', 'Right')], default='text-center', max_length=128)),
                ('intro_text_colour', models.CharField(choices=[('text-primary', 'Primary'), ('text-secondary', 'Secondary'), ('text-light', 'Light'), ('text-dark', 'Dark'), ('text-white', 'White'), ('text-body', 'Body'), ('text-muted', 'Muted'), ('text-white-50', 'White-50'), ('text-black-50', 'Black-50'), ('text-success', 'Success'), ('text-danger', 'Danger'), ('text-warning', 'Warning'), ('text-info', 'Info')], default='text-primary', max_length=128)),
                ('splash_image', models.ForeignKey(blank=True, help_text='Provide an image that spans the top of the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
