# Generated by Django 2.2.9 on 2020-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga_tracking_id',
            field=models.URLField(blank=True, help_text='Google Analytics Tracking ID (UA-#########-#)'),
        ),
    ]
